osx_image: xcode8.2
language: objective-c

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script:
  - xcodebuild -project CenteredCollectionView.xcodeproj -scheme CenteredCollectionView build-for-testing -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -project CenteredCollectionView.xcodeproj -scheme CenteredCollectionView run-tests -test-sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
